{
 "title": "Explore a GBIF dataset hll topn",
 "time": { "from": "1774-09-03T12:53:27.767Z", "to": "2021-12-31T23:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "minLat", "query": "1" },
   { "name": "maxLat", "query": "2" },
   { "name": "minLon", "query": "3" },
   { "name": "maxLon", "query": "4" },
   { "name": "search", "label": "Search" },
   {
    "name": "scientificname",
    "label": "Scientific name",
    "query": "Falco peregrinus Tunstall, 1771"
   },
   { "name": "recordedby", "label": "Recorded by" }
  ]
 },
 "panels": [
  {
   "title": "Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "set search_path to explore,public;\n\nSELECT time, hll_cardinality(hll_union_agg(hll_gbifid))\nFROM explore.cube\nWHERE $__timeFilter(time)\nAND grouping_scientificname = 1\n--AND scientificname % '$scientificname' --OR NULLIF(TRIM(CONCAT('$scientificname')), '') IS null)\nAND grouping_locality = 1\nAND grouping_recordedby = 1\nAND grouping_centro_id = 0\nAND grouping_time = 0\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), centro_id)\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Map",
   "type": "alexandra-trackmap-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "set search_path to explore,public;\n\nwith a as (\nSELECT \ncentro_id, \nhll_cardinality(hll_union_agg(hll_gbifid)) AS tooltip\nFROM explore.cube\nWHERE $__timeFilter(time)\nAND grouping_scientificname = 1\nAND grouping_locality = 1\nAND grouping_recordedby = 1\nAND grouping_centro_id = 0\nAND grouping_time = 0\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), centro_id)\ngroup by 1\n)\nselect \nST_Y (ST_Transform (centro_id, 4326)) AS latitude,\nST_X (ST_Transform (centro_id, 4326)) AS longitude,\ntooltip\nfrom a\n\n--GROUP BY 1,2"
    }
   ]
  },
  {
   "title": "Total records with geom",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "--set search_path to explore,public;\n\nSELECT hll_cardinality(hll_union_agg(hll_gbifid)) \n--hll_cardinality(hll_union_agg(hll_gbifid)),\n--SUM(hll_cardinality(hll_gbifid))\nFROM explore.cube\nWHERE $__timeFilter(time)\nAND grouping_scientificname = 1 --CASE WHEN NULLIF(TRIM(CONCAT($scientificname)), '') is null THEN 1 ELSE 0 END\n--AND (scientificname % '$scientificname' OR NULLIF(TRIM(CONCAT('$scientificname')), '') IS null)\nAND grouping_locality = 1 --CASE WHEN NULLIF(TRIM(CONCAT($locality)), '') is null THEN 1 ELSE 0 END\nAND grouping_recordedby = 1\nAND grouping_centro_id = 0\nAND grouping_time = 0\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), centro_id)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)"
    }
   ]
  },
  {
   "title": "Total records with geom",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "--set search_path to explore,public;\n\nSELECT hll_cardinality(hll_union_agg(hll_gbifid)) \n--hll_cardinality(hll_union_agg(hll_gbifid)),\n--SUM(hll_cardinality(hll_gbifid))\nFROM explore.cube\nWHERE $__timeFilter(time)\nAND grouping_scientificname = 1 --CASE WHEN NULLIF(TRIM(CONCAT($scientificname)), '') is null THEN 1 ELSE 0 END\n--AND (scientificname % '$scientificname' OR NULLIF(TRIM(CONCAT('$scientificname')), '') IS null)\nAND grouping_locality = 1 --CASE WHEN NULLIF(TRIM(CONCAT($locality)), '') is null THEN 1 ELSE 0 END\nAND grouping_recordedby = 1\nAND grouping_centro_id = 0\nAND grouping_time = 0\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), centro_id)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)"
    }
   ]
  },
  {
   "title": "Total records without geom and time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "--set search_path to explore,public;\n\nSELECT hll_cardinality(hll_union_agg(hll_gbifid)) \n--hll_cardinality(hll_union_agg(hll_gbifid)),\n--SUM(hll_cardinality(hll_gbifid))\nFROM explore.cube\n--WHERE $__timeFilter(time)\nWHERE grouping_scientificname = 1 --CASE WHEN NULLIF(TRIM(CONCAT($scientificname)), '') is null THEN 1 ELSE 0 END\n--AND (scientificname % '$scientificname' OR NULLIF(TRIM(CONCAT('$scientificname')), '') IS null)\nAND grouping_locality = 1 --CASE WHEN NULLIF(TRIM(CONCAT($locality)), '') is null THEN 1 ELSE 0 END\nAND grouping_recordedby = 1\nAND grouping_centro_id = 1\nAND grouping_time = 1\n--AND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), centro_id)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)"
    }
   ]
  },
  {
   "title": "Total clusters",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "--set search_path to explore,public;\n\nSELECT hll_cardinality(hll_union_agg(hll_cluster_id)) \n--hll_cardinality(hll_union_agg(hll_gbifid)),\n--SUM(hll_cardinality(hll_gbifid))\nFROM explore.cube\nWHERE $__timeFilter(time)\nAND grouping_scientificname = 1 --CASE WHEN NULLIF(TRIM(CONCAT($scientificname)), '') is null THEN 1 ELSE 0 END\n--AND (scientificname % '$scientificname' OR NULLIF(TRIM(CONCAT('$scientificname')), '') IS null)\nAND grouping_locality = 1 --CASE WHEN NULLIF(TRIM(CONCAT($locality)), '') is null THEN 1 ELSE 0 END\nAND grouping_recordedby = 1\nAND grouping_centro_id = 0\nAND grouping_time = 0\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), centro_id)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)"
    }
   ]
  },
  {
   "title": "Topn recorded by",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "set search_path to explore,public;\n\nSELECT recordedby,\nhll_cardinality(hll_union_agg(hll_gbifid))\nFROM explore.cube\nWHERE $__timeFilter(time)\nAND grouping_scientificname = 1\n--AND (scientificname % '$scientificname' OR NULLIF(TRIM(CONCAT('$scientificname')), '') IS null)\nAND grouping_locality = 1\nAND grouping_recordedby = 0\nAND grouping_centro_id = 0\nAND grouping_time = 0\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), centro_id)\nGROUP BY 1 ORDER BY 2 DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Topn scientific name",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "rawSql": "set search_path to explore,public;\n\nSELECT scientificname, \nhll_cardinality(hll_union_agg(hll_gbifid))\n--SUM(hll_cardinality(hll_gbifid))\nFROM explore.cube\nWHERE $__timeFilter(time)\nAND grouping_scientificname = 0\n--AND (scientificname % '$scientificname' OR NULLIF(TRIM(CONCAT('$scientificname')), '') IS null)\nAND grouping_locality = 1\nAND grouping_recordedby = 1\nAND grouping_centro_id = 0\nAND grouping_time = 0\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), centro_id)\nGROUP BY 1 \nORDER BY 2 desc\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT eventdate, COUNT(gbifid) OVER(), gbifid, catalognumber, scientificname, recordedby, occurrenceid, sex, preparations, locality\nFROM explore.gbif\nLEFT JOIN explore.recordedby ON gbif.recordedby_id = recordedby.id \nWHERE $__timeFilter(eventdate)\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nAND (tsv @@ websearch_to_tsquery('simple', '$search') OR NULLIF('$search', '') IS null)\n--AND (recordedby.name % '$recordedby' OR NULLIF('$recordedby', '') IS null)\n--AND (preparations IN ($preparations) OR NULLIF(TRIM(CONCAT($preparations)), '') IS null)\nORDER BY eventdate DESC\nLIMIT 100"
    }
   ]
  }
 ]
}